jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: pip install pyyaml
      
      - name: Validate workflow inputs
        run: .github/scripts/validate_workflow_inputs.py
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
          GITHUB_WORKFLOW_PATH: ${{ github.workflow_ref }}
